branches:
  main:
    mode: ContinuousDelivery
    tag:
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
ignore:
  sha:
    - 2a4757b270f7946122ba6622e3d2e72b2b2808a7