//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake.Common.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cake.Common.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Do not remove this test for UTF-8: if “Ω” doesn’t appear as greek uppercase omega letter enclosed in quotation marks, you should use an editor that supports UTF-8, not this one. --&gt;
        ///&lt;package xmlns=&quot;http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd&quot;&gt;
        ///  &lt;metadata&gt;
        ///    &lt;id&gt;The ID&lt;/id&gt;
        ///    &lt;title&gt;The title&lt;/title&gt;
        ///    &lt;version&gt;The version&lt;/version&gt;
        ///    &lt;authors&gt;Author #1,Author #2&lt;/authors&gt;
        ///    &lt;owners&gt;Owner #1,Owner #2&lt;/owners&gt;
        ///    &lt;summary&gt;The summa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChocolateyNuspec_Metadata {
            get {
                return ResourceManager.GetString("ChocolateyNuspec_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Do not remove this test for UTF-8: if “Ω” doesn’t appear as greek uppercase omega letter enclosed in quotation marks, you should use an editor that supports UTF-8, not this one. --&gt;
        ///&lt;package&gt;
        ///  &lt;metadata&gt;
        ///    &lt;id&gt;The ID&lt;/id&gt;
        ///    &lt;title&gt;The title&lt;/title&gt;
        ///    &lt;version&gt;The version&lt;/version&gt;
        ///    &lt;authors&gt;Author #1,Author #2&lt;/authors&gt;
        ///    &lt;owners&gt;Owner #1,Owner #2&lt;/owners&gt;
        ///    &lt;summary&gt;The summary&lt;/summary&gt;
        ///    &lt;description&gt;The description&lt;/description&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChocolateyNuspec_Metadata_WithoutNamespaces {
            get {
                return ResourceManager.GetString("ChocolateyNuspec_Metadata_WithoutNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Do not remove this test for UTF-8: if “Ω” doesn’t appear as greek uppercase omega letter enclosed in quotation marks, you should use an editor that supports UTF-8, not this one. --&gt;
        ///&lt;package xmlns=&quot;http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd&quot;&gt;
        ///  &lt;files&gt;
        ///    &lt;file src=&quot;tools\**&quot; target=&quot;tools&quot; /&gt;
        ///  &lt;/files&gt;
        ///&lt;/package&gt;.
        /// </summary>
        internal static string ChocolateyNuspec_NoMetadataElement {
            get {
                return ResourceManager.GetString("ChocolateyNuspec_NoMetadataElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Do not remove this test for UTF-8: if “Ω” doesn’t appear as greek uppercase omega letter enclosed in quotation marks, you should use an editor that supports UTF-8, not this one. --&gt;
        ///&lt;package xmlns=&quot;http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd&quot;&gt;
        ///  &lt;metadata /&gt;
        ///  &lt;files&gt;
        ///    &lt;file src=&quot;tools\**&quot; target=&quot;tools&quot; /&gt;
        ///  &lt;/files&gt;
        ///&lt;/package&gt;.
        /// </summary>
        internal static string ChocolateyNuspec_NoMetadataValues {
            get {
                return ResourceManager.GetString("ChocolateyNuspec_NoMetadataValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Do not remove this test for UTF-8: if “Ω” doesn’t appear as greek uppercase omega letter enclosed in quotation marks, you should use an editor that supports UTF-8, not this one. --&gt;
        ///&lt;package&gt;
        ///  &lt;metadata /&gt;
        ///  &lt;files&gt;
        ///    &lt;file src=&quot;tools\**&quot; target=&quot;tools&quot; /&gt;
        ///  &lt;/files&gt;
        ///&lt;/package&gt;.
        /// </summary>
        internal static string ChocolateyNuspec_NoMetadataValues_WithoutNamespaces {
            get {
                return ResourceManager.GetString("ChocolateyNuspec_NoMetadataValues_WithoutNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project ToolsVersion=&quot;12.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;MinimumVisualStudioVersion&gt;11.0&lt;/MinimumVisualStudioVersion&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; ==  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Csproj_IncompleteFile {
            get {
                return ResourceManager.GetString("Csproj_IncompleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project ToolsVersion=&quot;12.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;MinimumVisualStudioVersion&gt;11.0&lt;/MinimumVisualStudioVersion&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; ==  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Csproj_ProjectFile {
            get {
                return ResourceManager.GetString("Csproj_ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DuplicatesReport ToolsVersion=&quot;103.0&quot;&gt;
        ///  &lt;Statistics&gt;
        ///    &lt;CodebaseCost&gt;190358&lt;/CodebaseCost&gt;
        ///    &lt;TotalDuplicatesCost&gt;0&lt;/TotalDuplicatesCost&gt;
        ///    &lt;TotalFragmentsCost&gt;0&lt;/TotalFragmentsCost&gt;
        ///  &lt;/Statistics&gt;
        ///  &lt;Duplicates&gt;&lt;/Duplicates&gt;
        ///&lt;/DuplicatesReport&gt;.
        /// </summary>
        internal static string DupFinderReportNoDuplicates {
            get {
                return ResourceManager.GetString("DupFinderReportNoDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DuplicatesReport ToolsVersion=&quot;103.0&quot;&gt;
        ///  &lt;Statistics&gt;
        ///    &lt;CodebaseCost&gt;190358&lt;/CodebaseCost&gt;
        ///    &lt;TotalDuplicatesCost&gt;0&lt;/TotalDuplicatesCost&gt;
        ///    &lt;TotalFragmentsCost&gt;0&lt;/TotalFragmentsCost&gt;
        ///  &lt;/Statistics&gt;
        ///  &lt;Duplicates&gt;
        ///    &lt;Duplicate&gt;
        ///      &lt;Fragment&gt;
        ///        &lt;FileName&gt;LangFeatures\CLexer.cs&lt;/FileName&gt;
        ///        &lt;OffsetRange Start=&quot;4638&quot; End=&quot;4988&quot; /&gt;
        ///        &lt;LineRange Start=&quot;158&quot; End=&quot;168&quot; /&gt;
        ///      &lt;/Fragment&gt;
        ///      &lt;Fragment&gt;
        ///        &lt;FileName&gt;LangFe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DupFinderReportWithDuplicates {
            get {
                return ResourceManager.GetString("DupFinderReportWithDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Generated by InspectCode 8.2.1000.4527 --&gt;
        ///&lt;Report ToolsVersion=&quot;8.2&quot;&gt;
        ///  &lt;Information&gt;
        ///    &lt;Solution&gt;src\Cake.sln&lt;/Solution&gt;
        ///    &lt;InspectionScope&gt;
        ///      &lt;Element&gt;Solution&lt;/Element&gt;
        ///    &lt;/InspectionScope&gt;
        ///  &lt;/Information&gt;
        ///  &lt;IssueTypes&gt;&lt;/IssueTypes&gt;
        ///  &lt;Issues&gt;&lt;/Issues&gt;
        ///&lt;/Report&gt;.
        /// </summary>
        internal static string InspectCodeReportNoViolations {
            get {
                return ResourceManager.GetString("InspectCodeReportNoViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Generated by InspectCode 8.2.1000.4527 --&gt;
        ///&lt;Report ToolsVersion=&quot;8.2&quot;&gt;
        ///  &lt;Information&gt;
        ///    &lt;Solution&gt;src\Cake.sln&lt;/Solution&gt;
        ///    &lt;InspectionScope&gt;
        ///      &lt;Element&gt;Solution&lt;/Element&gt;
        ///    &lt;/InspectionScope&gt;
        ///  &lt;/Information&gt;
        ///  &lt;IssueTypes&gt;
        ///    &lt;IssueType Id=&quot;CSharpErrors&quot; Category=&quot;C# Compiler Errors&quot; Description=&quot;&quot; Severity=&quot;ERROR&quot; /&gt;
        ///  &lt;/IssueTypes&gt;
        ///  &lt;Issues&gt;
        ///    &lt;Project Name=&quot;Cake.Common&quot;&gt;
        ///      &lt;Issue TypeId=&quot;CSharpErrors&quot; File=&quot;Cake.Common.Tests\F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InspectCodeReportWithViolations {
            get {
                return ResourceManager.GetString("InspectCodeReportWithViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///
        ///// Information about this assembly is defined by the following attributes.
        ///// Change them to the values specific to your project.
        ///
        ///[assembly: AssemblyTitle (&quot;MonoDevelopAssemblyTitle&quot;)]
        ///[assembly: AssemblyDescription (&quot;MonoDevelopAssemblyDescription&quot;)]
        ///[assembly: AssemblyConfiguration (&quot;MonoDevelopConfiguration&quot;)]
        ///[assembly: AssemblyCompany (&quot;MonoDevelopCompany&quot;)]
        ///[assembly: AssemblyProduct (&quot;MonoDevelopProduct&quot;)]
        ///[assembly: Assembl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonoDevelopAssemblyInfo {
            get {
                return ResourceManager.GetString("MonoDevelopAssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;metadata xmlns=&quot;http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd&quot;&gt;
        ///    &lt;id&gt;The ID&lt;/id&gt;
        ///    &lt;version&gt;The version&lt;/version&gt;
        ///    &lt;title&gt;The title&lt;/title&gt;
        ///    &lt;authors&gt;Author #1,Author #2&lt;/authors&gt;
        ///    &lt;owners&gt;Owner #1,Owner #2&lt;/owners&gt;
        ///    &lt;description&gt;The description&lt;/description&gt;
        ///    &lt;summary&gt;The summary&lt;/summary&gt;
        ///    &lt;licenseUrl&gt;https://lic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nuspec_Metadata {
            get {
                return ResourceManager.GetString("Nuspec_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;metadata xmlns=&quot;http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd&quot;&gt;
        ///    &lt;id&gt;The ID&lt;/id&gt;
        ///    &lt;version&gt;The version&lt;/version&gt;
        ///    &lt;title&gt;The title&lt;/title&gt;
        ///    &lt;authors&gt;Author #1,Author #2&lt;/authors&gt;
        ///    &lt;owners&gt;Owner #1,Owner #2&lt;/owners&gt;
        ///    &lt;description&gt;The description&lt;/description&gt;
        ///    &lt;summary&gt;The summary&lt;/summary&gt;
        ///    &lt;licenseUrl&gt;https://lic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nuspec_Metadata_WithDependencies {
            get {
                return ResourceManager.GetString("Nuspec_Metadata_WithDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package&gt;
        ///  &lt;metadata&gt;
        ///    &lt;id&gt;The ID&lt;/id&gt;
        ///    &lt;version&gt;The version&lt;/version&gt;
        ///    &lt;title&gt;The title&lt;/title&gt;
        ///    &lt;authors&gt;Author #1,Author #2&lt;/authors&gt;
        ///    &lt;owners&gt;Owner #1,Owner #2&lt;/owners&gt;
        ///    &lt;description&gt;The description&lt;/description&gt;
        ///    &lt;summary&gt;The summary&lt;/summary&gt;
        ///    &lt;licenseUrl&gt;https://license.com&lt;/licenseUrl&gt;
        ///    &lt;projectUrl&gt;https://project.com&lt;/projectUrl&gt;
        ///    &lt;iconUrl&gt;https://icon.com&lt;/iconUrl&gt;
        ///    &lt;developmentDependency&gt;true&lt;/developmentDepende [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nuspec_Metadata_WithoutNamespaces {
            get {
                return ResourceManager.GetString("Nuspec_Metadata_WithoutNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package&gt;
        ///  &lt;metadata&gt;
        ///    &lt;id&gt;The ID&lt;/id&gt;
        ///    &lt;version&gt;The version&lt;/version&gt;
        ///    &lt;title&gt;The title&lt;/title&gt;
        ///    &lt;authors&gt;Author #1,Author #2&lt;/authors&gt;
        ///    &lt;owners&gt;Owner #1,Owner #2&lt;/owners&gt;
        ///    &lt;description&gt;The description&lt;/description&gt;
        ///    &lt;summary&gt;The summary&lt;/summary&gt;
        ///    &lt;licenseUrl&gt;https://license.com&lt;/licenseUrl&gt;
        ///    &lt;projectUrl&gt;https://project.com&lt;/projectUrl&gt;
        ///    &lt;iconUrl&gt;https://icon.com&lt;/iconUrl&gt;
        ///    &lt;developmentDependency&gt;true&lt;/developmentDepende [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nuspec_Metadata_WithoutNamespaces_WithDependencies {
            get {
                return ResourceManager.GetString("Nuspec_Metadata_WithoutNamespaces_WithDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;files&gt;
        ///    &lt;file src=&quot;Cake.Core.dll&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;Cake.Core.xml&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;Cake.Core.pdb&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;LICENSE&quot; /&gt;
        ///  &lt;/files&gt;
        ///&lt;/package&gt;.
        /// </summary>
        internal static string Nuspec_NoMetadataElement {
            get {
                return ResourceManager.GetString("Nuspec_NoMetadataElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;metadata xmlns=&quot;http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd&quot; /&gt;
        ///  &lt;files&gt;
        ///    &lt;file src=&quot;Cake.Core.dll&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;Cake.Core.xml&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;Cake.Core.pdb&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;LICENSE&quot; /&gt;
        ///  &lt;/files&gt;
        ///&lt;/package&gt;.
        /// </summary>
        internal static string Nuspec_NoMetadataValues {
            get {
                return ResourceManager.GetString("Nuspec_NoMetadataValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package&gt;
        ///  &lt;metadata /&gt;
        ///  &lt;files&gt;
        ///    &lt;file src=&quot;Cake.Core.dll&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;Cake.Core.xml&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;Cake.Core.pdb&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;LICENSE&quot; /&gt;
        ///  &lt;/files&gt;
        ///&lt;/package&gt;.
        /// </summary>
        internal static string Nuspec_NoMetadataValues_WithoutNamespaces {
            get {
                return ResourceManager.GetString("Nuspec_NoMetadataValues_WithoutNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;8.0.30703&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{AE8E29D0-6FF2-42D0-94EC-E725276A864D}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputTy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nuspec_ProjectFile {
            get {
                return ResourceManager.GetString("Nuspec_ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///
        ///// Information about this assembly is defined by the following attributes.
        ///// Change them to the values specific to your project.
        ///
        ///[assembly: AssemblyTitle(&quot;VisualStudioAssemblyTitle&quot;)]
        ///[assembly: AssemblyDescription(&quot;VisualStudioAssemblyDescription&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;VisualStudioConfiguration&quot;)]
        ///[assembly: AssemblyCompany(&quot;VisualStudioCompany&quot;)]
        ///[assembly: AssemblyProduct(&quot;VisualStudioProduct&quot;)]
        ///[assembly: Assembl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VisualStudioAssemblyInfo {
            get {
                return ResourceManager.GetString("VisualStudioAssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Cake.Common&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;M:Cake.Common.Solution.Project.ProjectAliases.ParseProject(Cake.Core.ICakeContext,Cake.Core.IO.FilePath)&quot;&gt;
        ///            &lt;summary&gt;
        ///            Parses project information from project file
        ///            &lt;/summary&gt;
        ///            &lt;param name=&quot;context&quot;&gt;The context.&lt;/param&gt;
        ///            &lt;param name=&quot;projectPath&quot;&gt;The project file path.&lt;/param&gt;
        ///            &lt;returns&gt;A parsed project.&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlDoc_ExampeCode_Cake_Common_Xml {
            get {
                return ResourceManager.GetString("XmlDoc_ExampeCode_Cake_Common_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;appSettings&gt;
        ///        &lt;add key=&quot;server&quot; value=&quot;testhost.somecompany.com&quot; /&gt;
        ///        &lt;add key=&quot;test&quot; value=&quot;true&quot; /&gt;
        ///    &lt;/appSettings&gt;
        ///    &lt;test&gt;test value&lt;/test&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string XmlPeek_Xml {
            get {
                return ResourceManager.GetString("XmlPeek_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///&lt;dict&gt;
        ///    &lt;key&gt;CFBundleDisplayName&lt;/key&gt;
        ///    &lt;string&gt;Cake&lt;/string&gt;
        ///&lt;/dict&gt;
        ///&lt;/plist&gt;
        ///.
        /// </summary>
        internal static string XmlPeek_Xml_Dtd {
            get {
                return ResourceManager.GetString("XmlPeek_Xml_Dtd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;appSettings&gt;
        ///        &lt;add key=&quot;server&quot; value=&quot;testhost.somecompany.com&quot; /&gt;
        ///        &lt;add key=&quot;test&quot; value=&quot;true&quot; /&gt;
        ///    &lt;/appSettings&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string XmlPoke_Xml {
            get {
                return ResourceManager.GetString("XmlPoke_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE plist PUBLIC &quot;-//Apple//DTD PLIST 1.0//EN&quot; &quot;http://www.apple.com/DTDs/PropertyList-1.0.dtd&quot;&gt;
        ///&lt;plist version=&quot;1.0&quot;&gt;
        ///&lt;dict&gt;
        ///    &lt;key&gt;CFBundleDisplayName&lt;/key&gt;
        ///    &lt;string&gt;Cake&lt;/string&gt;
        ///&lt;/dict&gt;
        ///&lt;/plist&gt;.
        /// </summary>
        internal static string XmlPoke_Xml_Dtd {
            get {
                return ResourceManager.GetString("XmlPoke_Xml_Dtd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;html&gt;&lt;body style=&quot;font-family:Arial;font-size:12pt;background-color:#EEEEEE&quot;&gt;&lt;div style=&quot;background-color:teal;color:white;padding:4px&quot;&gt;&lt;span style=&quot;font-weight:bold&quot;&gt;Belgian Waffles
        ///                    -
        ///                &lt;/span&gt;$5.95&lt;/div&gt;&lt;div style=&quot;margin-left:20px;margin-bottom:1em;font-size:10pt&quot;&gt;&lt;p&gt;Two of our famous Belgian Waffles with plenty of real maple syrup&lt;span style=&quot;font-style:italic&quot;&gt;
        ///                        (
        ///                        650
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlTransformation_Htm {
            get {
                return ResourceManager.GetString("XmlTransformation_Htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body style=&quot;font-family:Arial;font-size:12pt;background-color:#EEEEEE&quot;&gt;&lt;div style=&quot;background-color:teal;color:white;padding:4px&quot;&gt;&lt;span style=&quot;font-weight:bold&quot;&gt;Belgian Waffles
        ///                    -
        ///                &lt;/span&gt;$5.95&lt;/div&gt;&lt;div style=&quot;margin-left:20px;margin-bottom:1em;font-size:10pt&quot;&gt;&lt;p&gt;Two of our famous Belgian Waffles with plenty of real maple syrup&lt;span style=&quot;font-style:italic&quot;&gt;
        ///                        (
        ///                        650
        ///                        calories per serving)
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlTransformation_Htm_NoXmlDeclaration {
            get {
                return ResourceManager.GetString("XmlTransformation_Htm_NoXmlDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;breakfast_menu&gt;
        ///    &lt;food&gt;
        ///        &lt;name&gt;Belgian Waffles&lt;/name&gt;
        ///        &lt;price&gt;$5.95&lt;/price&gt;
        ///        &lt;description&gt;Two of our famous Belgian Waffles with plenty of real maple syrup&lt;/description&gt;
        ///        &lt;calories&gt;650&lt;/calories&gt;
        ///    &lt;/food&gt;
        ///    &lt;food&gt;
        ///        &lt;name&gt;Strawberry Belgian Waffles&lt;/name&gt;
        ///        &lt;price&gt;$7.95&lt;/price&gt;
        ///        &lt;description&gt;Light Belgian waffles covered with strawberries and whipped cream&lt;/description&gt;
        ///        &lt;calories&gt;900&lt;/calories&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlTransformation_Xml {
            get {
                return ResourceManager.GetString("XmlTransformation_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;html xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xsl:version=&quot;1.0&quot;&gt;
        ///    &lt;body style=&quot;font-family:Arial;font-size:12pt;background-color:#EEEEEE&quot;&gt;
        ///        &lt;xsl:for-each select=&quot;breakfast_menu/food&quot;&gt;
        ///            &lt;div style=&quot;background-color:teal;color:white;padding:4px&quot;&gt;
        ///                &lt;span style=&quot;font-weight:bold&quot;&gt;
        ///                    &lt;xsl:value-of select=&quot;name&quot; /&gt;
        ///                    -
        ///                &lt;/span&gt;
        ///                &lt;xsl:value-of select=&quot;price&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlTransformation_Xsl {
            get {
                return ResourceManager.GetString("XmlTransformation_Xsl", resourceCulture);
            }
        }
    }
}
