//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake.Common.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cake.Common.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;metadata xmlns=&quot;http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd&quot;&gt;
        ///    &lt;id&gt;The ID&lt;/id&gt;
        ///    &lt;version&gt;The version&lt;/version&gt;
        ///    &lt;title&gt;The title&lt;/title&gt;
        ///    &lt;authors&gt;Author #1,Author #2&lt;/authors&gt;
        ///    &lt;owners&gt;Owner #1,Owner #2&lt;/owners&gt;
        ///    &lt;description&gt;The description&lt;/description&gt;
        ///    &lt;summary&gt;The summary&lt;/summary&gt;
        ///    &lt;licenseUrl&gt;https://lic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nuspec_Metadata {
            get {
                return ResourceManager.GetString("Nuspec_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package&gt;
        ///  &lt;metadata&gt;
        ///    &lt;id&gt;The ID&lt;/id&gt;
        ///    &lt;version&gt;The version&lt;/version&gt;
        ///    &lt;title&gt;The title&lt;/title&gt;
        ///    &lt;authors&gt;Author #1,Author #2&lt;/authors&gt;
        ///    &lt;owners&gt;Owner #1,Owner #2&lt;/owners&gt;
        ///    &lt;description&gt;The description&lt;/description&gt;
        ///    &lt;summary&gt;The summary&lt;/summary&gt;
        ///    &lt;licenseUrl&gt;https://license.com&lt;/licenseUrl&gt;
        ///    &lt;projectUrl&gt;https://project.com&lt;/projectUrl&gt;
        ///    &lt;iconUrl&gt;https://icon.com&lt;/iconUrl&gt;
        ///    &lt;requireLicenseAcceptance&gt;true&lt;/requireLicenseA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nuspec_Metadata_WithoutNamespaces {
            get {
                return ResourceManager.GetString("Nuspec_Metadata_WithoutNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;files&gt;
        ///    &lt;file src=&quot;Cake.Core.dll&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;Cake.Core.xml&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;Cake.Core.pdb&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;LICENSE&quot; /&gt;
        ///  &lt;/files&gt;
        ///&lt;/package&gt;.
        /// </summary>
        internal static string Nuspec_NoMetadataElement {
            get {
                return ResourceManager.GetString("Nuspec_NoMetadataElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;metadata xmlns=&quot;http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd&quot; /&gt;
        ///  &lt;files&gt;
        ///    &lt;file src=&quot;Cake.Core.dll&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;Cake.Core.xml&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;Cake.Core.pdb&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;LICENSE&quot; /&gt;
        ///  &lt;/files&gt;
        ///&lt;/package&gt;.
        /// </summary>
        internal static string Nuspec_NoMetadataValues {
            get {
                return ResourceManager.GetString("Nuspec_NoMetadataValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package&gt;
        ///  &lt;metadata /&gt;
        ///  &lt;files&gt;
        ///    &lt;file src=&quot;Cake.Core.dll&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;Cake.Core.xml&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;Cake.Core.pdb&quot; target=&quot;lib/net45&quot; /&gt;
        ///    &lt;file src=&quot;LICENSE&quot; /&gt;
        ///  &lt;/files&gt;
        ///&lt;/package&gt;.
        /// </summary>
        internal static string Nuspec_NoMetadataValues_WithoutNamespaces {
            get {
                return ResourceManager.GetString("Nuspec_NoMetadataValues_WithoutNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Cake.Common&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;M:Cake.Common.Solution.Project.ProjectAliases.ParseProject(Cake.Core.ICakeContext,Cake.Core.IO.FilePath)&quot;&gt;
        ///            &lt;summary&gt;
        ///            Parses project information from project file
        ///            &lt;/summary&gt;
        ///            &lt;param name=&quot;context&quot;&gt;The context.&lt;/param&gt;
        ///            &lt;param name=&quot;projectPath&quot;&gt;The project file path.&lt;/param&gt;
        ///            &lt;returns&gt;A parsed project.&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlDoc_ExampeCode_Cake_Common_Xml {
            get {
                return ResourceManager.GetString("XmlDoc_ExampeCode_Cake_Common_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;appSettings&gt;
        ///        &lt;add key=&quot;server&quot; value=&quot;testhost.somecompany.com&quot; /&gt;
        ///        &lt;add key=&quot;test&quot; value=&quot;true&quot; /&gt;
        ///    &lt;/appSettings&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string XmlPoke_Xml {
            get {
                return ResourceManager.GetString("XmlPoke_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;html&gt;&lt;body style=&quot;font-family:Arial;font-size:12pt;background-color:#EEEEEE&quot;&gt;&lt;div style=&quot;background-color:teal;color:white;padding:4px&quot;&gt;&lt;span style=&quot;font-weight:bold&quot;&gt;Belgian Waffles
        ///                    -
        ///                &lt;/span&gt;$5.95&lt;/div&gt;&lt;div style=&quot;margin-left:20px;margin-bottom:1em;font-size:10pt&quot;&gt;&lt;p&gt;Two of our famous Belgian Waffles with plenty of real maple syrup&lt;span style=&quot;font-style:italic&quot;&gt;
        ///                        (
        ///                        650
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlTransformation_Htm {
            get {
                return ResourceManager.GetString("XmlTransformation_Htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body style=&quot;font-family:Arial;font-size:12pt;background-color:#EEEEEE&quot;&gt;&lt;div style=&quot;background-color:teal;color:white;padding:4px&quot;&gt;&lt;span style=&quot;font-weight:bold&quot;&gt;Belgian Waffles
        ///                    -
        ///                &lt;/span&gt;$5.95&lt;/div&gt;&lt;div style=&quot;margin-left:20px;margin-bottom:1em;font-size:10pt&quot;&gt;&lt;p&gt;Two of our famous Belgian Waffles with plenty of real maple syrup&lt;span style=&quot;font-style:italic&quot;&gt;
        ///                        (
        ///                        650
        ///                        calories per serving)
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlTransformation_Htm_NoXmlDeclaration {
            get {
                return ResourceManager.GetString("XmlTransformation_Htm_NoXmlDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;breakfast_menu&gt;
        ///    &lt;food&gt;
        ///        &lt;name&gt;Belgian Waffles&lt;/name&gt;
        ///        &lt;price&gt;$5.95&lt;/price&gt;
        ///        &lt;description&gt;Two of our famous Belgian Waffles with plenty of real maple syrup&lt;/description&gt;
        ///        &lt;calories&gt;650&lt;/calories&gt;
        ///    &lt;/food&gt;
        ///    &lt;food&gt;
        ///        &lt;name&gt;Strawberry Belgian Waffles&lt;/name&gt;
        ///        &lt;price&gt;$7.95&lt;/price&gt;
        ///        &lt;description&gt;Light Belgian waffles covered with strawberries and whipped cream&lt;/description&gt;
        ///        &lt;calories&gt;900&lt;/calories&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlTransformation_Xml {
            get {
                return ResourceManager.GetString("XmlTransformation_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;html xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xsl:version=&quot;1.0&quot;&gt;
        ///    &lt;body style=&quot;font-family:Arial;font-size:12pt;background-color:#EEEEEE&quot;&gt;
        ///        &lt;xsl:for-each select=&quot;breakfast_menu/food&quot;&gt;
        ///            &lt;div style=&quot;background-color:teal;color:white;padding:4px&quot;&gt;
        ///                &lt;span style=&quot;font-weight:bold&quot;&gt;
        ///                    &lt;xsl:value-of select=&quot;name&quot; /&gt;
        ///                    -
        ///                &lt;/span&gt;
        ///                &lt;xsl:value-of select=&quot;price&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlTransformation_Xsl {
            get {
                return ResourceManager.GetString("XmlTransformation_Xsl", resourceCulture);
            }
        }
    }
}
