<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Cake.NuGet</AssemblyName>
    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCpu</PlatformTarget>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <!-- Package specific metadata -->
  <PropertyGroup>
    <Description>Cake Module providing NuGet install capabilities for i.e. preprocessor directives like #addin, #tool and #load</Description>
  </PropertyGroup>
  <!-- Import shared functionality -->
  <Import Project="..\Shared.msbuild" />
  <!-- Project references -->
  <ItemGroup>
    <ProjectReference Include="..\Cake.Core\Cake.Core.csproj" />
  </ItemGroup>
  <!-- Global packages -->
  <ItemGroup>
    <PackageReference Include="NuGet.Credentials"/>
    <PackageReference Include="NuGet.Frameworks"/>
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="NuGet.Protocol" />
    <PackageReference Include="NuGet.Packaging" />
    <PackageReference Include="NuGet.Resolver" />
    <PackageReference Include="NuGet.Common" />
    <PackageReference Include="Newtonsoft.Json" />

    <!-- Pin nuget transitive packages vulnerability issues NuGet.Packaging -->
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
  </ItemGroup>

  <ItemGroup>
    <!-- Refreshed by build.cake Update-Portable-Rid-Graph when global.json changes. -->
    <EmbeddedResource Include="PortableRuntimeIdentifierGraph.json" />
  </ItemGroup>

</Project>