//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("The Title")]
[assembly: AssemblyDescription("The Description")]
[assembly: AssemblyCompany("The Company")]
[assembly: AssemblyProduct("The Product")]
[assembly: AssemblyVersion("1.0")]
[assembly: AssemblyFileVersion("1.0.1")]
[assembly: AssemblyInformationalVersion("1.0-@")]
[assembly: AssemblyCopyright("The Copyright")]
[assembly: AssemblyTrademark("The Trademark")]
[assembly: AssemblyConfiguration("The Configuration")]
[assembly: Guid("4147f50a-8743-4393-a414-efc707d4ba2c")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

[assembly: InternalsVisibleTo("Eeny")]
[assembly: InternalsVisibleTo("Meeny")]
[assembly: InternalsVisibleTo("Miny")]
[assembly: InternalsVisibleTo("Moe")]

