// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Cake")]
[assembly: AssemblyVersionAttribute("0.1.3")]
[assembly: AssemblyFileVersionAttribute("0.1.3")]
[assembly: AssemblyInformationalVersionAttribute("0.1.3")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Patrik Svensson 2014")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.3";
    }
}
